@EmployeeManagementSystem_HostAddress = http://localhost:5292
@ContentType = application/json

GET {{EmployeeManagementSystem_HostAddress}}/api/Employee/employees
Accept: {{ContentType}}

###
GET {{EmployeeManagementSystem_HostAddress}}/api/Employee/employees/details
Accept: {{ContentType}}
###
